import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

const resources = {
  en: {
    translation: {
      header: { home: 'Home', howItWorks: 'How it Works', signIn: 'Sign In', signUp: 'Sign Up', logout: 'LogOut', welcome: 'Welcome' },
      login: { title: 'Login to your account', email: 'Your Email', password: 'Your Password', submit: 'submit', noAccount: "Don't have an account?", createAccount: 'Create a new account' },
      signup: { title: 'Join the network', email: 'Email', firstName: 'First Name', lastName: 'Last Name', username: 'User Name', password: 'Password', agreeJoin: 'Agree and Join', haveAccount: 'Already have an account?', signIn: 'Sign in' },
      common: { loading: 'Loading…', error: 'Something went wrong' },
      home: { questions: 'Questions', askQuestion: 'Ask Question', signIn: 'Sign In', empty: 'No questions yet' },
      pagination: { prev: 'Prev', next: 'Next' },
      ask: { stepsTitle: 'Steps to write a good question', step1: 'Summarize your problem in a one-line title.', step2: 'Describe your problem in more detail.', step3: 'Describe what you tried and what you expected to happen.', step4: 'Review your question and post it to the site.', askTitle: 'Ask a public question', goToQuestions: 'Go to Question page', titlePlaceholder: 'Title', descriptionPlaceholder: 'Question Description...', tagPlaceholder: 'Tag', imageUrlOptional: 'Image URL (optional)', suggestTags: 'Suggest Tags', findSimilar: 'Find Similar', answered: '✓ answered', answersCount: '{{count}} answers', postButton: 'Post Your Question', postSuccess: 'Question created successfully', postFailed: 'Failed to post question' },
      about: { title: 'About Evangadi Networks Q&A', body: 'Evangadi Networks Q&A helps learners ask questions and get answers from the community. Share your challenges, help others, and grow together.' },
      question: { heading: 'Question', community: 'Answer From The Community', answerTop: 'Answer The Top Question', answerPlaceholder: 'Your Answer...', postButton: 'Post Your Answer', postSuccess: 'Answer posted successfully', postFailed: 'Failed to post answer', noAnswers: 'No answers yet', liveQA: 'Live Q&A', sendMessage: 'Send a message', send: 'Send', typing: '{{username}} is typing…', translatePrompt: 'Translate…', aiSummary: 'AI Summary', askCopilot: 'Ask Copilot' },
      admin: { title: 'Admin', tabs: { dashboard: 'Dashboard', users: 'Users', moderation: 'Moderation', qa: 'Q&A', system: 'System', logs: 'Logs' }, latestUsers: 'Latest Users', latestQuestions: 'Latest Questions', latestAnswers: 'Latest Answers', latestNotifications: 'Latest Notifications', metrics: { title: 'Metrics', totalUsers: 'Total Users', totalQuestions: 'Total Questions', totalAnswers: 'Total Answers', last24hUsers: 'Last 24h Users', last24hQuestions: 'Last 24h Questions', last24hAnswers: 'Last 24h Answers' }, health: { title: 'Health', api: 'API', db: 'DB', uptime: 'Uptime', port: 'Port' }, activity: 'Activity', contentOversight: 'Question & Answer Oversight', filters: { byUserEmail: 'Filter by user/email', reportedOnly: 'Reported only', filter: 'Filter' }, table: { title: 'Title', user: 'User', username: 'Username', email: 'Email', role: 'Role', status: 'Status', lastLogin: 'Last Login', date: 'Date', actions: 'Actions', answer: 'Answer' }, actions: { edit: 'Edit', delete: 'Delete', pin: 'Pin', unpin: 'Unpin', open: 'Open', dismiss: 'Dismiss', bulkDelete: 'Bulk Delete Selected', viewActivity: 'View Activity', grantAdmin: 'Grant Admin', revokeAdmin: 'Revoke Admin', grantModerator: 'Grant Moderator', revokeModerator: 'Revoke Moderator', suspend: 'Suspend', unsuspend: 'Unsuspend', search: 'Search' }, users: { title: 'User Management', searchPlaceholder: 'Search by username or email', status: { all: 'All', admins: 'Admins', suspended: 'Suspended', active: 'Active' } }, system: { categories: 'Categories', name: 'Name', description: 'Description', add: 'Add', siteSettings: 'Site Settings', announcementBanner: 'Announcement Banner', save: 'Save', resetEmailSubject: 'Reset Email Subject', resetEmailBody: 'Reset Email Body (use {{link}})', saveSubject: 'Save Subject', saveBody: 'Save Body', maintenanceMode: 'Maintenance Mode', off: 'Off', on: 'On', siteName: 'Site Name', tags: 'Tags', newTag: 'New tag', rename: 'Rename' }, logs: { audit: 'Admin Audit Trail', recentLogins: 'Recent Logins', errors: 'Error Logs' }, chartLegend: { questions: 'Questions', answers: 'Answers' } },
      notifications: { title: 'Notifications', newQuestion: 'New question: {{title}}', newAnswerBy: 'New answer by {{username}}', bestAnswerSelected: 'Best answer selected', markRead: 'Mark read' },
      errors: { fillAll: 'Please fill in all fields', invalidCredentials: 'Invalid credentials', passwordLength: 'Password must be at least 8 characters', fillRequired: 'Please provide all required fields', registrationFailed: 'Registration failed' }
    }
  },
  am: {
    translation: {
      header: { home: 'መነሻ', howItWorks: 'እንዴት እንሰራ', signIn: 'መግባት', signUp: 'መመዝገብ', logout: 'መውጣት', welcome: 'እንኳን ደህና መጣህ' },
      login: { title: 'መለያዎትን ያስገቡ', email: 'ኢሜልዎ', password: 'የይለፍ ቃልዎ', submit: 'ማስገባት', noAccount: 'መለያ የለዎትም?', createAccount: 'አዲስ መለያ ፍጠር' },
      signup: { title: 'መለያ ፍጠር', email: 'ኢሜል', firstName: 'ስም', lastName: 'የአባት ስም', username: 'የተጠቃሚ ስም', password: 'የይለፍ ቃል', agreeJoin: 'ተቀላቀል', haveAccount: 'መለያ አለዎት?', signIn: 'ግባ' },
      common: { loading: 'በመጫን ላይ…', error: 'ችግኝ ተፈጥሯል' },
      home: { questions: 'ጥያቄዎች', askQuestion: 'ጥያቄ ጠይቅ', signIn: 'ግባ', empty: 'ጥያቄ የለም' },
      pagination: { prev: 'ከዚህ በፊት', next: 'ቀጣይ' },
      ask: { stepsTitle: 'ጥሩ ጥያቄ ለመጻፍ ደረጃዎች', step1: 'ጭራሽ ርዕስ ላይ ጉዳይህን አስተዋውቅ.', step2: 'ጉዳይህን በተጨማሪ ዝርዝር ግለጽ.', step3: 'የሞከርህን እና የጠበቅህን ያሳይ.', step4: 'ጥያቄዎትን ክለሳ አድርገው ለማስቀመጥ.', askTitle: 'የሕዝብ ጥያቄ ይጠይቁ', goToQuestions: 'ወደ ጥያቄ ገጽ ሂዱ', titlePlaceholder: 'ርዕስ', descriptionPlaceholder: 'የጥያቄ መግለጫ...', tagPlaceholder: 'መለያ', imageUrlOptional: 'የምስል አድራሻ (አማራጭ)', suggestTags: 'ቴጎች አስተውል', findSimilar: 'ተመሳሳይ ፈልግ', answered: '✓ ተመልሷል', answersCount: '{{count}} መልስ', postButton: 'ጥያቄዎትን አስቀምጥ', postSuccess: 'ጥያቄ ተሳክቷል', postFailed: 'ጥያቄ አልተሳካም' },
      about: { title: 'ስለ Evangadi Networks Q&A', body: 'Evangadi Networks Q&A ተማሪዎችን ጥያቄ እንዲጠይቁ እና መልስ እንዲያገኙ ይረዳል። ፈተናዎችዎን ያጋሩ፣ ሌሎችን ይርዱ እና በአንድነት ይድጋሉ።' },
      question: { heading: 'ጥያቄ', community: 'መልስ ከማህበረሰብ', answerTop: 'ከፍተኛው ጥያቄ መልስ', answerPlaceholder: 'መልስዎ...', postButton: 'መልስ ላክ', postSuccess: 'መልስ ተሳክቷል', postFailed: 'መልስ አልተሳካም', noAnswers: 'መልስ የለም', liveQA: 'ቀጥታ Q&A', sendMessage: 'መልዕክት ላክ', send: 'ላክ', typing: '{{username}} በመጻፍ ላይ…', translatePrompt: 'ተርጉም…', aiSummary: 'AI ድርጊት', askCopilot: 'Copilot ጠይቅ' },
      admin: { title: 'አስተዳዳሪ', tabs: { dashboard: 'ዳሽቦርድ', users: 'ተጠቃሚዎች', moderation: 'ቁጥጥር', qa: 'Q&A', system: 'ሲስተም', logs: 'ሎጎች' }, latestUsers: 'አዲስ ተጠቃሚዎች', latestQuestions: 'አዲስ ጥያቄዎች', latestAnswers: 'አዲስ መልሶች', latestNotifications: 'አዲስ ማሳወቂያዎች', metrics: { title: 'ሚትሪክስ', totalUsers: 'ጠቅላላ ተጠቃሚዎች', totalQuestions: 'ጠቅላላ ጥያቄዎች', totalAnswers: 'ጠቅላላ መልሶች', last24hUsers: '24 ሰአት ተጠቃሚ', last24hQuestions: '24 ሰአት ጥያቄ', last24hAnswers: '24 ሰአት መልስ' }, health: { title: 'ጤና', api: 'API', db: 'DB', uptime: 'ጊዜ', port: 'ፖርት' }, activity: 'እንቅስቃሴ', contentOversight: 'ጥያቄና መልስ ቁጥጥር', filters: { byUserEmail: 'በተጠቃሚ/ኢሜል አጣራ', reportedOnly: 'ብቻ የተጠቁ', filter: 'አጣራ' }, table: { title: 'ርዕስ', user: 'ተጠቃሚ', username: 'የተጠቃሚ ስም', email: 'ኢሜል', role: 'ሚና', status: 'ሁኔታ', lastLogin: 'የመግቢያ ጊዜ', date: 'ቀን', actions: 'እርምጃዎች', answer: 'መልስ' }, actions: { edit: 'አርትእ', delete: 'ሰርዝ', pin: 'ምልክት', unpin: 'አርቅ', open: 'ክፈት', dismiss: 'አትርፍ', bulkDelete: 'ብዙ ሰርዝ', viewActivity: 'እንቅስቃሴ ይመልከቱ', grantAdmin: 'አድሚን ስጥ', revokeAdmin: 'አድሚን ወስድ', grantModerator: 'ሞደሬተር ስጥ', revokeModerator: 'ሞደሬተር ወስድ', suspend: 'አግድ', unsuspend: 'አንሳ', search: 'ፈልግ' }, users: { title: 'የተጠቃሚ አስተዳደር', searchPlaceholder: 'በስም ወይም ኢሜል ፈልግ', status: { all: 'ሁሉ', admins: 'አድሚን', suspended: 'ታግዷል', active: 'ንቁ' } }, system: { categories: 'ምድቦች', name: 'ስም', description: 'መግለጫ', add: 'ጨምር', siteSettings: 'የሳይት ግብዓት', announcementBanner: 'ማስታወቂያ ባነር', save: 'አስቀምጥ', resetEmailSubject: 'የኢሜል ርዕስ አድስ', resetEmailBody: 'የኢሜል እስክሪፕት ({{link}} ተጠቀም)', saveSubject: 'ርዕስ አስቀምጥ', saveBody: 'አካል አስቀምጥ', maintenanceMode: 'ማስተካከያ ሁነታ', off: 'ጠፍቷል', on: 'በሥራ ላይ', siteName: 'የሳይት ስም', tags: 'ቴጎች', newTag: 'አዲስ ቴግ', rename: 'ስም ቀይር' }, logs: { audit: 'የአስተዳዳሪ ደረጃ', recentLogins: 'የቅርብ መግቢያዎች', errors: 'ስህተቶች' }, chartLegend: { questions: 'ጥያቄዎች', answers: 'መልሶች' } },
      notifications: { title: 'ማሳወቂያዎች', newQuestion: 'አዲስ ጥያቄ: {{title}}', newAnswerBy: 'አዲስ መልስ በ {{username}}', bestAnswerSelected: 'ምርጥ መልስ ተመርጧል', markRead: 'አንብብ ምልክት' },
      errors: { fillAll: 'ሁሉንም መስኮች አሙሉ', invalidCredentials: 'መረጃ የተሳሳተ', passwordLength: 'የይለፍ ቃል ቢያንስ 8 አቃፊ', fillRequired: 'አስፈላጊ መረጃ ያቅርቡ', registrationFailed: 'መመዝገብ አልተሳካም' }
    }
  },
  gez: {
    translation: {
      header: { home: 'መነሻ', howItWorks: 'እንዴት ይሰራ', signIn: 'መግባት', signUp: 'መመዝገብ', logout: 'መውጣት', welcome: 'እንኳን ደህና መጣህ' },
      login: { title: 'መለያ መግቢ', email: 'ኢሜል', password: 'የይለፍ ቃል', submit: 'አስገባ', noAccount: 'መለያ የለም?', createAccount: 'አዲስ መለያ ፍጠር' },
      signup: { title: 'መመዝገብ', email: 'ኢሜል', firstName: 'ስም', lastName: 'የአባት ስም', username: 'የተጠቃሚ ስም', password: 'የይለፍ ቃል', agreeJoin: 'ተቀላቀል', haveAccount: 'መለያ አለ?', signIn: 'ግባ' },
      common: { loading: 'በመጫን ላይ…', error: 'ችግኝ' },
      home: { questions: 'ጥያቄ', askQuestion: 'ጥያቄ ጠይቅ', signIn: 'ግባ', empty: 'ጥያቄ የለም' },
      pagination: { prev: 'ቀዳሚ', next: 'ቀጣይ' },
      ask: { stepsTitle: 'የጥያቄ ደረጃዎች', step1: 'ርዕስ አጭር ጭራሽ.', step2: 'ጉዳይ ግለጽ.', step3: 'የሞከርህን እና ተመኘህን አሳይ.', step4: 'ክለሳ አድርግ አስቀምጥ.', askTitle: 'የሕዝብ ጥያቄ ጠይቅ', goToQuestions: 'ወደ ጥያቄ ገጽ', titlePlaceholder: 'ርዕስ', descriptionPlaceholder: 'መግለጫ...', tagPlaceholder: 'መለያ', imageUrlOptional: 'የምስል አድራሻ (አማራጭ)', suggestTags: 'ቴጎች አስተውል', findSimilar: 'ተመሳሳይ ፈልግ', answered: '✓ ተመልሷል', answersCount: '{{count}} መልስ', postButton: 'ጥያቄ አስቀምጥ', postSuccess: 'ተሳክቷል', postFailed: 'አልተሳካም' },
      about: { title: 'ስለ Evangadi Networks Q&A', body: 'Evangadi Networks Q&A ጥያቄን ለመጠየቅና መልስ ለማግኘት ይረዳ። ጉዳዮችን ካጋሩ ሌሎችን አግዙ እና በአንድነት ይድጋሉ።' },
      question: { heading: 'ጥያቄ', community: 'መልስ ከማህበረሰብ', answerTop: 'ከፍተኛ ጥያቄ መልስ', answerPlaceholder: 'መልስ...', postButton: 'መልስ ላክ', postSuccess: 'ተሳክቷል', postFailed: 'አልተሳካም', noAnswers: 'መልስ የለም', liveQA: 'ቀጥታ Q&A', sendMessage: 'መልዕክት ላክ', send: 'ላክ', typing: '{{username}} በመጻፍ ላይ…', translatePrompt: 'ተርጉም…', aiSummary: 'AI አጭር መግለጫ', askCopilot: 'Copilot ጠይቅ' },
      admin: { title: 'አስተዳዳሪ', tabs: { dashboard: 'ዳሽቦርድ', users: 'ተጠቃሚ', moderation: 'ቁጥጥር', qa: 'Q&A', system: 'ሲስተም', logs: 'ሎጎች' }, latestUsers: 'አዲስ ተጠቃሚ', latestQuestions: 'አዲስ ጥያቄ', latestAnswers: 'አዲስ መልስ', latestNotifications: 'አዲስ ማሳወቂያ', metrics: { title: 'ሚትሪክስ', totalUsers: 'ጠቅላላ ተጠቃሚ', totalQuestions: 'ጠቅላላ ጥያቄ', totalAnswers: 'ጠቅላላ መልስ', last24hUsers: '24 ሰአት ተጠቃሚ', last24hQuestions: '24 ሰአት ጥያቄ', last24hAnswers: '24 ሰአት መልስ' }, health: { title: 'ጤና', api: 'API', db: 'DB', uptime: 'ጊዜ', port: 'ፖርት' }, activity: 'እንቅስቃሴ', contentOversight: 'ጥያቄ እና መልስ ቁጥጥር', filters: { byUserEmail: 'በተጠቃሚ/ኢሜል አጣራ', reportedOnly: 'ብቻ የተጠቁ', filter: 'አጣራ' }, table: { title: 'ርዕስ', user: 'ተጠቃሚ', date: 'ቀን', actions: 'እርምጃ', answer: 'መልስ' }, actions: { edit: 'አርትእ', delete: 'ሰርዝ', pin: 'ምልክት', unpin: 'አርቅ', open: 'ክፈት', dismiss: 'አትርፍ', bulkDelete: 'ብዙ ሰርዝ', viewActivity: 'እንቅስቃሴ ይመልከቱ', grantAdmin: 'አድሚን ስጥ', revokeAdmin: 'አድሚን ወስድ', grantModerator: 'ሞደሬተር ስጥ', revokeModerator: 'ሞደሬተር ወስድ', suspend: 'አግድ', unsuspend: 'አንሳ', search: 'ፈልግ' }, users: { title: 'የተጠቃሚ አስተዳደር', searchPlaceholder: 'በስም ወይም ኢሜል ፈልግ', status: { all: 'ሁሉ', admins: 'አድሚን', suspended: 'ታግዷል', active: 'ንቁ' } }, system: { categories: 'ምድቦች', name: 'ስም', description: 'መግለጫ', add: 'ጨምር', siteSettings: 'የሳይት ግብዓት', announcementBanner: 'ማስታወቂያ ባነር', save: 'አስቀምጥ', resetEmailSubject: 'የኢሜል ርዕስ አድስ', resetEmailBody: 'የኢሜል አካል ({{link}} ተጠቀም)', saveSubject: 'ርዕስ አስቀምጥ', saveBody: 'አካል አስቀምጥ', maintenanceMode: 'ማስተካከያ ሁነታ', off: 'ጠፍቷል', on: 'በሥራ ላይ', siteName: 'የሳይት ስም', tags: 'ቴጎች', newTag: 'አዲስ ቴግ', rename: 'ስም ቀይር' }, logs: { audit: 'የአስተዳዳሪ ደረጃ', recentLogins: 'የቅርብ መግቢያዎች', errors: 'ስህተቶች' }, chartLegend: { questions: 'ጥያቄ', answers: 'መልስ' } },
      notifications: { title: 'ማሳወቂያ', newQuestion: 'አዲስ ጥያቄ: {{title}}', newAnswerBy: 'አዲስ መልስ በ {{username}}', bestAnswerSelected: 'ምርጥ መልስ ተመርጧል', markRead: 'አንብብ ምልክት' },
      errors: { fillAll: 'ሁሉን ሙሉ', invalidCredentials: 'መረጃ ተሳስቷል', passwordLength: 'ከ8 ቁምፊ በላይ', fillRequired: 'አስፈላጊ መረጃ', registrationFailed: 'መመዝገብ አልተሳካ' }
    }
  }
}

i18n.use(initReactI18next).init({
  resources,
  lng: 'en',
  fallbackLng: 'en',
  interpolation: { escapeValue: false }
})

export default i18n
